### ISSUE TITLE
Need help for testing

### ISSUE THREAD

**Issue by alexivaner** [Renater/SIPMediaGW#13]
HI, thanks for a great project. Could you help me elaborate this more:

Once the virtual machine is up, you can join a conference from your preferred SIP softphone:

_sip:your_conference_name@192.168.75.13 (Direct access)
sip:0@192.168.75.13 (IVR access => Jitsi Meet only)
Depending on [BROWSE_FILE](https://github.com/Renater/SIPMediaGW/blob/114ee4be29e0460132a0c018b8bbd94c72728522/.env#L12) and [WEBRTC_DOMAIN](https://github.com/Renater/SIPMediaGW/blob/114ee4be29e0460132a0c018b8bbd94c72728522/.env#L13) variables, the corresponding webconference is:

jitsi (default): https://meet.jit.si/your_conference_name
or
bigbluebutton: https://demo.bigbluebutton.org/rooms/your_conference_name/join_

I currently use microsip and x-lite but I am still confused about how to test this one and do direct calls, I also want to confirm if is it by default will forward to meet.jit.si? How to check if the video from the sip call is already inside the conference? And how do we setup "YOUR_CONFERENCE_NAME" part? I am sorry for this silly question because I am a beginner in SIP.

btw, is it possible if I use FreeSwitch that converts H323 call to SIP then use SIPMediaGW to forward it to jitsi meet? Thank you so much for your time.

**Comment by nicotyze** [comment]
Hi, 
For a testing example, please have a look at [this](https://community.jitsi.org/t/sipmediagw-a-docker-based-gateway-jun-26-6h-ago/124568/63?u=nicolas_tizon)
Yes, by default SIPMediaGW is configured with meet.jit.si as you can see on the last screen shot. By default, the conference name is a number (n digits before entering #) => 1234 in this basic example....
This project is focused on SIP. I have no idea about how to convert H323 call to SIP and don't know either if it's something doable...

**Comment by alexivaner** [comment]
Hi Nicotyze, thank you for reply. Do you know why I always getting this error?

![image](https://github.com/Renater/SIPMediaGW/assets/57290644/39f9c3c4-3edc-40ac-bfa4-f603a57ebde3)
```
Aug 17 09:14:01 ubuntu-focal systemd[1]: Stopped sipmediagw.
Aug 17 09:14:01 ubuntu-focal systemd[1]: Starting sipmediagw...
Aug 17 09:14:07 ubuntu-focal systemd[1]: sipmediagw.service: Succeeded.
Aug 17 09:14:07 ubuntu-focal systemd[1]: Started sipmediagw.
Aug 17 09:14:08 ubuntu-focal systemd[1]: sipmediagw.service: Scheduled restart job, restart counter is at 201.
Aug 17 09:14:08 ubuntu-focal systemd[1]: Stopped sipmediagw.
Aug 17 09:14:08 ubuntu-focal systemd[1]: Starting sipmediagw...
```
