### ISSUE TITLE
Iframe error

### ISSUE THREAD

**Issue by callmemaxim** [Renater/SIPMediaGW#19]
Hello! Could you please help me with issue?

Sipmediagw container restarting after several seconds
Here is the log:

Baresip: Populated 1 account
Baresip: contact: creating contacts template .baresip/contacts
Baresip: Populated 3 contacts
Baresip: Populated 3 audio codecs
Baresip: Populated 0 audio filters
Baresip: Populated 3 video codecs
Baresip: Populated 0 video filters
Baresip: baresip is ready.
Baresip: 10.0.2.15.mediagw.0@123.123.123.123: (prio 0) {0/TCP/v4} 200 OK (kamailio (5.6.3 (x86_64/linux))) [1 binding]
Event: Browsing mod name: jitsi
Baresip: ua: stop all (forced=0)
Event: Iframe error

So, I've added print(e) to jitsi.py:

   def unset(self):
        try:
            self.driver.execute_script("window.JitsiMeetUIHelper.room.jitsiApiClient.dispose()")
            start = time.time()
            while time.time() - start < 5:
                if self.driver.execute_script("return document.getElementsByTagName('iframe')[0];"):
                    time.sleep(1)
                else:
                    break
        except Exception as e:
            print(e)
            print("Iframe error", flush=True)

And the log looks like:
Event: Browsing mod name: jitsi
Baresip: ua: stop all (forced=0)
Event: 'list' object has no attribute 'execute_script'
Event: Iframe error

Is the problem related to jitsi.py or baresip?
Thanks for the help and your project in advance!

**Comment by nicotyze** [comment]
Hello, I've reproduced the problem with a fresh Vagrant deployment. It seems to be related to OS and packages installation/update issues. 
I've updated the [OS version](https://github.com/Renater/SIPMediaGW/blob/c48e972a0da8dd1c8f8aa4bd36c46808ffeaffb9/test/Vagrantfile#L5). With this new OS configuration, the container does not restart continuously and my test call succeed.
