### ISSUE TITLE
Adding a JWT to the room URL

### ISSUE THREAD

**Issue by HamzaKhait** [Renater/SIPMediaGW#23]
Hello guys,

I'm trying to connect the SIPMediaGW to a JWT-protected Jitsi service where all users must provide a JWT, but I cannot find where to add the JWT in the SIPMediaGW environment file, even though it's supported by the [JitsiMeetUIHelper](https://github.com/Renater/JitsiMeetUIHelper).

Any ideas ? 

Thank you in advance 🙏

**Comment by daimoc** [comment]
Hi Hamza, thanks for the question.
This optios was not present in the SIPMediaGW env, so I made a pull request to add it : #24 

Regards

**Comment by HamzaKhait** [comment]
It works like a charm. Thank you so much @daimoc  🙏
