### ISSUE TITLE
Support for Jaas

### ISSUE THREAD

**Issue by calloquy-mark-baker** [Renater/SIPMediaGW#5]
Amazing project! Lots of really solid work here.

We're a Jaas customer (i.e. using 8x8.vc and vpass-magic-cookie app IDs). Before I go through and try to completely understand every line of code and potentially mangle a refactor, do you have thoughts on how we might be able to utilize this project with a paid Jaas configuration?  

As I understand it, the main difference is that the browser would need to go to https://WEBRTC_DOMAIN/vpass-magic-cookie-secret/room.

Apologies if this is not the way you'd like this question presented, and Thank You again for all the great work!

**Comment by nicotyze** [comment]
Thanks for the comment ! No problem for me to use the issue tracker for that :)
Indeed, our goal at Renater is to provide SIPMediaGW as a large scale service to our users community.

About Jaas, I've never tried it but yes, it should work in the way you described it (with potentially slight adaptations needed in jitsi.py, depending on the specific versions/configurations of Jaas...).

This is not well documented yet, but SIPMediaGW relies on [JitsiMeetUIHelper](https://github.com/Renater/JitsiMeetUIHelper) (for the Jitsi part). By default a UI Helper is embedded in the docker image but it is also possible to use your own by setting [UI_HELPER_PATH](https://github.com/Renater/SIPMediaGW/blob/0c85beb4ac565c10aed2ab048b5f49c407332fe8/browsing/jitsi.py#L20) variable.
This UI helper allows to customize the way a user interact with a JitsiMeet instance. Among others, the UI Helper implements:

- an audio+video prompt (IVR), where to enter a room number
- an overlay menu for remote control (DTMF mappings)
- conference mapper requests to retrieve a room name from a specific number (10 digits with api.jitsi.net/conferenceMapper). The conference mapper URL  can be set in the[ .env](https://github.com/Renater/SIPMediaGW/blob/0c85beb4ac565c10aed2ab048b5f49c407332fe8/.env#L14). 

It is also possible to add a basic JWT authentication logic in the UI Helper (=>will allow the SIP endpoint to initiate a meeting).

**Comment by nicotyze** [comment]
Before closing  the issue: PRs are welcome :)
