### ISSUE TITLE
SIPMediaGW behind nat

### ISSUE THREAD

**Issue by BHoury** [Renater/SIPMediaGW#6]
Hello,

We test this solution with BBB.
We have install SIPMediaGW on VM with have local IP and and accessible from the internet with public  (SIPMediaGW behind nat).
The service are ok but when we join a conference with public IP we have a not relaying message. (With local ip it work)

Thanks
B.Houry

**Comment by nicotyze** [comment]
The problem probably comes from the kamailio configuration. The TURN server (for the media part)  could be problematic with NAT as well.
I assume that kamailio and coturn run on the same machine with pub_addr and local_addr being respectively the public and the local addresses of the VM. 
Then the [environment variables](https://github.com/Renater/SIPMediaGW/blob/0c85beb4ac565c10aed2ab048b5f49c407332fe8/test/provision.sh#L39-L42) should be adapted as follows:
- SIP_DOMAIN=pub_addr
- PUBLIC_IP=pub_addr
- LOCAL_IP=local_addr
- STUN_SRV=pub_addr

Useful commands to check kamailio configuration:
- docker exec -it kamailio kamctl srv sockets
- docker exec -it kamailio kamctl srv aliases
