### ISSUE TITLE
Failed Installing kamailio/kamailio:5.6.3-bullseye

### ISSUE THREAD

**Issue by SamjiDiamond** [Renater/SIPMediaGW#7]
Hi,

Running the setup using provision.sh, I got an error attached below.

Kindly assist on the way forward.

![image](https://user-images.githubusercontent.com/47559418/233293392-5ccc01ac-bb98-422e-8894-d1a6c2ae670b.png)

**Comment by nicotyze** [comment]
Hi,
Base docker images for kamailio have recently been moved from dockerhub to [github](https://github.com/kamailio/kamailio-docker/pkgs/container/kamailio). My [last commit](https://github.com/Renater/SIPMediaGW/commit/546923389308c282d71754099d1ab604c9c9712c) should fix the problem.
